<?php

/**
 *
 *
 * @author Brendan Howard
 * @category ANM293 - Advanced PHP
 *
 * Final Exam
 *
 */

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" >
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en" >
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Style-Type" content="text/css" />
<meta name="Author" content="LifeStoryNet LLC" />
<meta name="description" content="ANM293 Final Exam: Page 2" />
<style type="text/css"></style>
<link rel="SHORTCUT ICON" href="/favicon.ico" />
<title>ANM293 Final Exam: Page 2</title>
</head>
<body>
	<h1>Final Exam</h1>
	<h2>Page 2</h2>    
	<p>
	Proin facilisis sem et dui interdum pharetra. Duis lorem nisi, blandit id 
	fermentum quis, vehicula id est. Mauris leo lorem, tempor non fermentum vel, 
	lobortis a nunc. Nullam felis dolor, semper nec malesuada vitae, tincidunt 
	sed odio. Vivamus lacinia porttitor turpis id malesuada. Aenean ac posuere 
	sem. Nunc in mauris vel dui consequat lacinia at sit amet mi. Nullam vel 
	pulvinar eros. Aenean euismod aliquam odio, hendrerit tincidunt velit 
	euismod vitae. Quisque et arcu ligula, in congue metus. In hac habitasse 
	platea dictumst. Nullam nec arcu quis libero dignissim varius. Aliquam 
	turpis ligula, dictum nec dignissim sed, feugiat ac odio. Vestibulum 
	lobortis rhoncus diam, et eleifend tortor pharetra sed. Sed diam eros, 
	pellentesque quis tristique sit amet, luctus ut justo. Mauris commodo 
	cursus sapien at dictum. In elementum tincidunt arcu, eget sagittis nisi 
	iaculis sit amet.
	</p>
	
	<p>
	Sed tincidunt purus sed justo tristique at cursus sem facilisis. Nam at 
	dolor ut elit euismod laoreet. Pellentesque egestas urna non odio tristique 
	lobortis. Nullam ultrices porta lacinia. Suspendisse tincidunt blandit 
	lectus vitae aliquet. Sed id lacinia libero. Vestibulum venenatis laoreet 
	odio, quis tristique sapien condimentum nec. Integer lacus mi, rutrum ut 
	fringilla ac, rutrum vel magna. Maecenas lectus risus, eleifend tempus 
	pretium convallis, luctus nec nunc. Sed quis lorem a ligula euismod 
	hendrerit quis vitae neque. Mauris sagittis tortor ac erat convallis 
	lobortis. Pellentesque eleifend pretium nunc. Vestibulum tortor ipsum, 
	eleifend vitae egestas at, laoreet eu augue. In hac habitasse platea 
	dictumst. Aenean fringilla iaculis augue. Maecenas eu libero vitae dui 
	commodo imperdiet vel at orci. Etiam nibh lorem, cursus sed rutrum ut, 
	iaculis vel turpis. Proin laoreet tristique odio quis vestibulum. Mauris 
	in magna urna. Nunc suscipit, justo eget elementum mattis, lorem metus 
	convallis eros, vel convallis nisl nisl at lorem.
	</p>
	
	<p>
	Integer tristique sagittis eleifend. Nam sed magna nec nisl posuere 
	convallis nec scelerisque elit. Nam tempus mauris in eros pharetra quis 
	ultrices ipsum blandit. Integer et pellentesque nulla. Vestibulum id orci 
	lorem. Ut convallis fringilla ipsum, in posuere erat hendrerit eu. Donec a
	 augue quis lectus gravida mollis. Sed eget augue nisi, sed varius libero. 
	 In hac habitasse platea dictumst. Sed ac ipsum nisl. Donec at magna sapien. 
	 Fusce id enim a massa rhoncus consectetur. In vel massa lorem. Vestibulum 
	 aliquam dui eu metus ultrices ut elementum lectus pellentesque. Sed id eros 
	 tortor.
	</p>

	<p>
	Ut iaculis enim id arcu vestibulum pellentesque. Etiam pharetra egestas 
	felis, at dapibus turpis tincidunt ut. Etiam sed eros elit, quis scelerisque 
	dui. Fusce eget ligula ac ante adipiscing rutrum vel at sapien. Donec 
	dictum, eros id scelerisque mollis, leo risus mattis odio, sit amet faucibus 
	mi neque et metus. Vivamus libero sapien, fermentum vel eleifend at, 
	eleifend ac lectus. Pellentesque pellentesque, tellus non interdum viverra, 
	odio mauris faucibus libero, ac hendrerit risus libero euismod elit. Donec 
	rhoncus iaculis justo, quis tristique ipsum egestas quis. Duis massa elit, 
	vehicula sit amet commodo et, volutpat ut dolor. Morbi ac ornare ante. Duis 
	id dui diam, id pharetra mi. Vivamus vulputate mi eget mauris tincidunt 
	venenatis. Sed libero elit, placerat ac mattis viverra, luctus nec nisl.
	</p>
	
	<p>
	Sed iaculis quam ut arcu dictum pretium aliquam urna posuere. Fusce bibendum 
	sagittis augue id semper. Phasellus pretium sodales ornare. Pellentesque non 
	lectus ut enim congue dapibus. Quisque et elit velit. Aenean mi odio, dictum 
	vitae rutrum et, pulvinar in sem. Sed molestie accumsan eros in tempor. Proin 
	quis metus eget odio euismod venenatis non eget augue. Sed gravida hendrerit 
	nisi et facilisis. Donec laoreet interdum vestibulum. Nulla lobortis dui in 
	sem fringilla sollicitudin. Maecenas at scelerisque erat. 
	</p>

	<h3>ANM-293, Tuesdays 6:00pm - 8:40pm</h3>

</body>
</html>
    